### ISSUE TITLE
ERROR] Invalid key length

### ISSUE THREAD

**Issue by mrranger** [dimaslesmana/steamhourboost-discord#1]
Failed to add new Steam account!

**Comment by dimaslesmana** [comment]
> Failed to add new Steam account!

Hello,

Make sure you have a **.env** file whose content is based on the content in the **.env.example** file. For invalid key length, ensure that the value of `CRYPTO_SECRET_KEY` is 32 characters long.

**Comment by mrranger** [comment]
I'm stupid, I thought that he generates it himself, thanks!
