### ISSUE TITLE
error when trying to add accounts

### ISSUE THREAD

**Issue by FrazeDev** [dimaslesmana/steamhourboost-discord#12]
hello, as title says it doesn't let me add accounts and there is no errors in console 
![image](https://github.com/dimaslesmana/steamhourboost-discord/assets/72148172/a8373e6d-44f1-4e12-b397-64c731ebd549)
everything else works fines as /user info only this doesn't work 
![image](https://github.com/dimaslesmana/steamhourboost-discord/assets/72148172/94f7134d-ca8d-4db3-bfaa-a655d5c41fc6)

**Comment by dimaslesmana** [comment]
Make sure the value of `CRYPTO_SECRET_KEY` is 32 characters long. #1

**Comment by FrazeDev** [comment]
> Make sure the value of `CRYPTO_SECRET_KEY` is 32 characters long. #1

can you tell me where can i get it ? because i can't find it

**Comment by dimaslesmana** [comment]
> > Make sure the value of `CRYPTO_SECRET_KEY` is 32 characters long. #1
> 
> can you tell me where can i get it ? because i can't find it

You can use or generate any random string as long as it is 32 characters long. Remember to keep it a secret.
