### ISSUE TITLE
how to solve

### ISSUE THREAD

**Issue by FCK-SteL** [dimaslesmana/steamhourboost-discord#2]
ERROR] NODE_ENV is required

**Comment by FCK-SteL** [comment]
i solved this, but this time. I can't add accounts via discord server, bot starting to "i m thinking..." and nothing happening

**Comment by FCK-SteL** [comment]
50
  51 static async getAllRunning() {
  52   try {
→ 53     return await prisma.steamAccounts.findMany(
error: Error validating datasource `db`: the URL must start with the protocol `file:`.
  -->  schema.prisma:10
   |
 9 |   provider = "sqlite"
10 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1

**Comment by dimaslesmana** [comment]
> 50 51 static async getAllRunning() { 52 try { → 53 return await prisma.steamAccounts.findMany( error: Error validating datasource `db`: the URL must start with the protocol `file:`. --> schema.prisma:10 | 9 | provider = "sqlite" 10 | url = env("DATABASE_URL") |
> 
> Validation Error Count: 1

Hello,

What database are you using?

**Comment by sWeEZzYY** [comment]
can u add me on discord? SwENzZZYY#3766
