### ISSUE TITLE
Need help changing to mysql database.

### ISSUE THREAD

**Issue by Andriuxas** [dimaslesmana/steamhourboost-discord#5]
Hello, I need some help changing it to mysql database so It would work.

Invalid `prisma.steamAccounts.findMany()` invocation in
C:\Users\Andriuxas\Downloads\discord hour\steamhourboost-discord-master\src\services\steam-account.service.js:59:56

  56
  57 static async getAllRunning() {
  58   try {
→ 59     const steamAccounts = await prisma.steamAccounts.findMany(
error: Error validating datasource `db`: the URL must start with the protocol `file:`.
  -->  schema.prisma:10
   |
 9 |   provider = "sqlite"
10 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1

**Comment by dimaslesmana** [comment]
> Hello, I need some help changing it to mysql database so It would work.
> 
> Invalid `prisma.steamAccounts.findMany()` invocation in C:\Users\Andriuxas\Downloads\discord hour\steamhourboost-discord-master\src\services\steam-account.service.js:59:56
> 
> 56 57 static async getAllRunning() { 58 try { → 59 const steamAccounts = await prisma.steamAccounts.findMany( error: Error validating datasource `db`: the URL must start with the protocol `file:`. --> schema.prisma:10 | 9 | provider = "sqlite" 10 | url = env("DATABASE_URL") |
> 
> Validation Error Count: 1

You can change the datasource provider in the **schema.prisma** file and replace it with the `mysql` provider. After that, change the `DATABASE_URL` in the **.env** file to the [MySQL connection string](https://www.prisma.io/docs/reference/database-reference/connection-urls#mysql). Then rerun the commands contained in the Setup section (numbers 3 to 5).

**Comment by Andriuxas** [comment]
![image](https://user-images.githubusercontent.com/64680439/217296107-91bcdb91-595c-402b-9809-80970b64f061.png)
What is difference of free license and premium?

**Comment by Andriuxas** [comment]
Also hours doesn't actually get added. Only recent activity hours adds, but not real hours.
![image](https://user-images.githubusercontent.com/64680439/217299754-f9f77561-6154-4dd6-9f66-ad997d25b877.png)

**Comment by Andriuxas** [comment]
I have one more question. How much accounts its possible to boost at once?

**Comment by dimaslesmana** [comment]
> ![image](https://user-images.githubusercontent.com/64680439/217296107-91bcdb91-595c-402b-9809-80970b64f061.png) What is difference of free license and premium?

Free: 1 account & 1 games.
Premium: Unlimited account & 30 games.


> Also hours doesn't actually get added. Only recent activity hours adds, but not real hours. ![image](https://user-images.githubusercontent.com/64680439/217299754-f9f77561-6154-4dd6-9f66-ad997d25b877.png)

It may take time to see the changes.


> I have one more question. How much accounts its possible to boost at once?

I haven't tested it for multiple accounts at once. For example, about 100 accounts and up. But there are no specific restrictions.
