### ISSUE TITLE
Reconnecting problem.

### ISSUE THREAD

**Issue by Andriuxas** [dimaslesmana/steamhourboost-discord#6]
I'm having reconnecting problem. After some time it writes reconnecting and asks to enter steam guard again. Would It be possible to fix it?
![image](https://user-images.githubusercontent.com/64680439/232202615-3b30de31-83c2-4a82-b329-595e729a1bf1.png)

**Comment by dimaslesmana** [comment]
> I'm having reconnecting problem. After some time it writes reconnecting and asks to enter steam guard again. Would It be possible to fix it? ![image](https://user-images.githubusercontent.com/64680439/232202615-3b30de31-83c2-4a82-b329-595e729a1bf1.png)

Because the authentication method using the login key is deprecated _([https://github.com/DoctorMcKay/node-steam-user#login-key-deprecation](https://github.com/DoctorMcKay/node-steam-user#login-key-deprecation))_, I have replaced it by using a refresh token. You can see the implementation in the **development** branch of this repository.

**Comment by Andriuxas** [comment]
Is it possible to fix?

**Comment by dimaslesmana** [comment]
> Is it possible to fix?

Yes, by using the refresh token authentication method instead of login key.

**Comment by Andriuxas** [comment]
> > I'm having reconnecting problem. After some time it writes reconnecting and asks to enter steam guard again. Would It be possible to fix it? ![image](https://user-images.githubusercontent.com/64680439/232202615-3b30de31-83c2-4a82-b329-595e729a1bf1.png)
> 
> Because the authentication method using the login key is deprecated _(https://github.com/DoctorMcKay/node-steam-user#login-key-deprecation)_, I have replaced it by using a refresh token. You can see the implementation in the **development** branch of this repository.

So you have implement to this repository by using refresh token?

**Comment by dimaslesmana** [comment]
> > > I'm having reconnecting problem. After some time it writes reconnecting and asks to enter steam guard again. Would It be possible to fix it? ![image](https://user-images.githubusercontent.com/64680439/232202615-3b30de31-83c2-4a82-b329-595e729a1bf1.png)
> > 
> > Because the authentication method using the login key is deprecated _(https://github.com/DoctorMcKay/node-steam-user#login-key-deprecation)_, I have replaced it by using a refresh token. You can see the implementation in the **development** branch of this repository.
> 
> So you have implemented already to this repository refresh token? 

Yes.

**Comment by Andriuxas** [comment]
So I have to downloaded your latest build right and it should work fine? 
![image](https://user-images.githubusercontent.com/64680439/232238658-020017bf-b18c-4b8e-9c2c-1e944b8605eb.png)

**Comment by dimaslesmana** [comment]
Change to the development branch first, then download the source code from that branch.

**Comment by Andriuxas** [comment]
Alright thanks I was dumb. :D

**Comment by Andriuxas** [comment]
I have one more question. Is it possible to boost game for example csgo, and play at the same time other game?
