### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by WarlockZera** [dimaslesmana/steamhourboost-discord#7]
When the bot is stopped, the steam account is still idle and the discord bot is still online, and when the bot is started again it is in a loop informing that there is already a session and tries in 40 minutes.

**Comment by WarlockZera** [comment]
yes, there is only one instance running, however when closing the node.js cmd the bot is still online in discord and the steam account in idle

**Comment by dimaslesmana** [comment]
The Discord bot online status sometimes is delayed. As for Steam, can you check the status from the Steam Friends & Chat window?
